### ISSUE TITLE
Merge conflict commited

### ISSUE THREAD

**Issue by krihal** [felipap/toml-python#2]
The parser (https://github.com/f03lipe/toml-python/blob/master/tomlpython/parser.py) have a conflict commited in it at line 63.

<<<<<<< HEAD
#         self.reader.discardLine()

```
    self.reader.discartLine()
```

> > > > > > > d1442b78e77d36d368da55f2ff3aae97bf3959fc

**Comment by felipap** [comment]
How come I didn't see that? Thanks for reporting.
