### ISSUE TITLE
spec compliance

### ISSUE THREAD

**Issue by BurntSushi** [felipap/toml-python#3]
I've [created a gist](https://gist.github.com/BurntSushi/5080369) with the results of running your parser against [toml-test](https://github.com/BurntSushi/toml-test).

There are some failed tests. A few of them seem to be related to the fact that datetimes in your parser are represented as strings. So feel free to interpret those tests how you see fit.

**Comment by felipap** [comment]
The `json` module can't serialize the dictionary unless the dates are represented as strings, so that was just a quick, dirty fix - one I'm deeply ashamed of. :P I've just fixed this one bug. I'm working on the others. _Thanks for the heads-up!_

**Comment by felipap** [comment]
It's now passing 47/51 tests. I'm still figuring out how to pass _key-special-chars_.

**Comment by felipap** [comment]
@BurntSushi, why should duplicating a keygroup raise an error?

**Comment by felipap** [comment]
@BurntSushi, to your understanding, is this valid toml?

``` toml
[foo.bar]
car = 3
[foo.bar]
bike = 4
```

**Comment by BurntSushi** [comment]
No. **Not** valid TOML. My evidence is from the spec:

> Be careful not to overwrite previous keys. That's dumb. And should produce an error.

The example in the spec given is:

``` toml
# DO NOT WANT
[fruit]
type = "apple"

[fruit.type]
apple = "yes"
```

You might want to interpret this as "keys cannot override keygroups and vice versa", and I think that is legitimate. Reasonable people can disagree. We need a clarification. From keeping up with the issue tracker, my sense is that @mojombo wants to ban all duplicate key definitions.

**Comment by BurntSushi** [comment]
Looks like there is already an issue open (that I forgot about) asking for a clarification [#145](https://github.com/mojombo/toml/issues/145)

**Comment by felipap** [comment]
Since the issue was clarified (see https://github.com/mojombo/toml/commit/0f5a49449cc1aaebbaa31e4938816f1c18e426ef), I've updated the program to **disallow keygroup duplication** and I'm closing this. Thanks for the support! :+1:
